from .alpaca import Alpaca
from .alligator import Alligator
from .boa import Boa
from .cobra import Cobra
from .copperhead import Copperhead
from .dolphin import Dolphin
from .donkey import Donkey
from .goat import Goat
from .goldfish import Goldfish
from .goose import Goose
from .llama import Llama
from .mallard import Mallard
from .mamba import Mamba
from .piranha import Piranha
from .ratsnake import RatSnake
from .shark import Shark
from .sheep import Sheep
